POST  http://localhost:3003/purchase
Content-Type: application/json

{
    "person_name": "Jazz",
    "product_name": "Whiskas",
    "indication_code": "cUDFwV"
}

###

GET http://localhost:3003/buyers

###

GET  http://localhost:3003/buyers
Content-Type: application/json

{
    "person_code": "783c1023-a537-41e9-ba53-81f5af4ab1d6"
}

###
